apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  selector:
    matchLabels:
      app: nginx-blue
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-blue
        # version: "1.0"
    spec:
      containers:
      - name: nginx-blue
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: nginx-conf
          subPath: index.html
      volumes:
      - name: nginx-conf
        configMap:
           name: index-html-configmap-blue